# Generated by Django 6.1.1 on 2026-09-11 19:34

import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_organisation_and_roles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('unit', models.CharField(help_text='Singular, e.g. "box".', max_length=50)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('order_size', models.PositiveIntegerField(blank=True, null=True)),
                ('pinned_to_reorder_at', models.DateTimeField(blank=True, null=True)),
                ('barcode', models.CharField(blank=True, max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.organisation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ordered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expected_at', models.DateTimeField(blank=True)),
                ('received_qty', models.PositiveIntegerField(blank=True, null=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_lines', to='stock.item')),
                ('ordered_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.organisation')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('lead_days', models.PositiveSmallIntegerField(default=5, help_text='Calendar days from order to delivery.')),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('notes', models.TextField(blank=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.organisation')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='stock.supplier'),
        ),
        migrations.CreateModel(
            name='StockEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('kind', models.CharField(choices=[('count', 'Counted'), ('used', 'Used'), ('low', 'Running low'), ('out', 'Out'), ('received', 'Received')], max_length=20)),
                ('qty', models.PositiveIntegerField(blank=True, null=True)),
                ('client_id', models.UUIDField(blank=True, null=True, unique=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='stock.item')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.organisation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('kind__in', ['count', 'used', 'received']), _negated=True), ('qty__isnull', False), _connector='OR'), name='stock_event_qty_required', violation_error_message='Counts, uses and deliveries need a quantity.')],
            },
        ),
        migrations.AddConstraint(
            model_name='supplier',
            constraint=models.UniqueConstraint(models.F('organisation'), django.db.models.functions.text.Lower('name'), name='stock_supplier_name_unique_per_org', violation_error_message='You already have a supplier with that name.'),
        ),
    ]
