# Generated by Django 6.1.1 on 2026-09-12 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_supplier_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoResetState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
    ]
