# Generated by Django 6.1.1 on 2026-09-13 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_item_reorder_requested_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogueProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('unit', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=100)),
                ('position', models.PositiveIntegerField(help_text='Display order: by category, then as listed.')),
            ],
        ),
        migrations.CreateModel(
            name='CatalogueSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('website', models.URLField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='other_suppliers',
            field=models.ManyToManyField(blank=True, related_name='backup_items', to='stock.supplier'),
        ),
        migrations.AddField(
            model_name='orderline',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_lines', to='stock.supplier'),
        ),
        migrations.CreateModel(
            name='CatalogueOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='stock.catalogueproduct')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='stock.cataloguesupplier')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.AddField(
            model_name='catalogueproduct',
            name='suppliers',
            field=models.ManyToManyField(related_name='products', through='stock.CatalogueOffer', to='stock.cataloguesupplier'),
        ),
        migrations.AddConstraint(
            model_name='catalogueoffer',
            constraint=models.UniqueConstraint(fields=('product', 'supplier'), name='stock_catalogue_offer_unique'),
        ),
    ]
