# Generated by Django 6.1.1 on 2026-09-17 09:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_practice_login_and_staff_codes'),
        ('stock', '0007_orderline_supplier_required_and_catalogue_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='supplier_sku',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='orderline',
            name='order_ref',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(blank=True, max_length=200)),
                ('issued_on', models.DateField(blank=True, null=True)),
                ('order_ref', models.CharField(blank=True, max_length=64)),
                ('totals_ok', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('parsed', 'Ready to check'), ('complete', 'Received'), ('partial', 'Partly received'), ('ignored', 'Already imported'), ('conflict', 'Needs checking')], default='parsed', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.organisation')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='stock.supplier')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(blank=True, max_length=64)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('qty', models.PositiveIntegerField(blank=True, null=True)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('line_total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='stock.invoice')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.organisation')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
