# Generated by Django 6.1.1 on 2026-09-17 09:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_practice_login_and_staff_codes'),
        ('stock', '0008_invoice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceline',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_lines', to='stock.item'),
        ),
        migrations.AddField(
            model_name='item',
            name='name_embedding',
            field=models.JSONField(blank=True, editable=False, null=True),
        ),
        migrations.CreateModel(
            name='ItemAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=200)),
                ('raw_name', models.CharField(max_length=200)),
                ('method', models.CharField(choices=[('sku', 'Same supplier code'), ('alias', 'Matched before'), ('exact', 'Same name'), ('synonym', 'Another name for it'), ('fuzzy', 'Close spelling'), ('semantic', 'Similar meaning'), ('manual', 'Picked by hand')], max_length=20)),
                ('confidence', models.FloatField()),
                ('source', models.CharField(choices=[('invoice', 'Invoice'), ('import', 'Import'), ('manual', 'By hand')], max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reverted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='stock.item')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.organisation')),
                ('reverted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('source_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='stock.invoice')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('reverted_at__isnull', True)), fields=('organisation', 'key'), name='stock_itemalias_live_key_unique')],
            },
        ),
    ]
