# Generated by Django 6.1.1 on 2026-09-17 10:14

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_practice_login_and_staff_codes'),
        ('stock', '0009_item_alias'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='checksum',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='invoice',
            name='force_reason',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='invoice',
            name='forced_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='invoice',
            name='source_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('checksum', ''), _negated=True), models.Q(('status', 'ignored'), _negated=True), ('forced_by__isnull', True)), fields=('organisation', 'checksum'), name='stock_invoice_file_once'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(models.F('organisation'), models.F('supplier'), django.db.models.functions.text.Lower('invoice_number'), condition=models.Q(('supplier__isnull', False), models.Q(('invoice_number', ''), _negated=True), models.Q(('status', 'ignored'), _negated=True), ('forced_by__isnull', True)), name='stock_invoice_number_once_per_supplier'),
        ),
    ]
