# Generated by Django 6.1.1 on 2026-09-17 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0011_invoice_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceline',
            name='order_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_lines', to='stock.orderline'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('parsed', 'Nothing received yet'), ('complete', 'Received'), ('partial', 'Partly received'), ('ignored', 'Already imported'), ('conflict', 'Needs checking')], default='parsed', max_length=20),
        ),
    ]
