# Generated by Django 6.1.1 on 2026-09-17 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0012_invoice_line_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderline',
            name='split_from',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remainder', to='stock.orderline'),
        ),
    ]
