# Generated by Django 6.1.1 on 2026-09-17 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0013_orderline_split_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderline',
            name='price_before',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
