# Generated by Django 6.1.1 on 2026-09-17 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0014_orderline_price_before'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='undo_snapshot',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='undo_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
