# Generated by Django 6.1.1 on 2026-09-17 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0015_invoice_undo_snapshot_invoice_undo_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceline',
            name='stock_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='stock.stockevent'),
        ),
    ]
