# Generated by Django 6.1.1 on 2026-09-17 20:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_organisation_setup_dismissed_at'),
        ('stock', '0016_invoiceline_stock_event'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='gst_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='supplier_gst_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='invoice',
            name='total_excl_gst',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='total_incl_gst',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.CreateModel(
            name='InvoiceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=100)),
                ('data', models.BinaryField()),
                ('byte_size', models.PositiveIntegerField()),
                ('checksum', models.CharField(db_index=True, max_length=64)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('retain_until', models.DateField()),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='stock.invoice')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.organisation')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('organisation', 'checksum'), name='stock_invoice_document_once')],
            },
        ),
    ]
