# Generated by Django 6.1.1 on 2026-09-13 03:08

import django.core.validators
import django.db.models.functions.text
import django.db.models.lookups
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_organisation_and_roles'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_practice_login',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='pin',
            field=models.CharField(blank=True, max_length=4, null=True, validators=[django.core.validators.RegexValidator('^(\\d{2}|\\d{4})$', 'Use digits only: 2 for an assistant, 4 for a manager.')], verbose_name='code'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='email address'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(fields=('organisation', 'pin'), name='accounts_user_pin_unique_per_practice', violation_error_message='Someone at this practice already uses that code.'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('email__isnull', False), ('pin__isnull', False), _connector='OR'), name='accounts_user_has_a_way_in', violation_error_message='Everyone needs an email address or a code to sign in with.'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('pin__isnull', True), models.Q(models.Q(('role', 'admin')), django.db.models.lookups.Exact(django.db.models.functions.text.Length('pin'), 4)), models.Q(models.Q(('role', 'assistant')), django.db.models.lookups.Exact(django.db.models.functions.text.Length('pin'), 2)), _connector='OR'), name='accounts_user_code_length_matches_role', violation_error_message='Managers need a 4-digit code, and assistants a 2-digit one.'),
        ),
    ]
