# Generated by Django 6.1.1 on 2026-09-13 01:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_organisation_and_roles'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_practice_login',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='pin',
            field=models.CharField(blank=True, max_length=2, null=True, validators=[django.core.validators.RegexValidator('^\\d{2}$', 'Use two digits, like 07.')], verbose_name='code'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='email address'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(fields=('organisation', 'pin'), name='accounts_user_pin_unique_per_practice', violation_error_message='Someone at this practice already uses that code.'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('email__isnull', False), ('pin__isnull', False), _connector='OR'), name='accounts_user_has_a_way_in', violation_error_message='Everyone needs an email address or a code to sign in with.'),
        ),
    ]
