# Generated by Django 6.1.1 on 2026-09-17 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_practice_login_and_staff_codes'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='setup_dismissed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
